"""
Extension 2 — Dialogue System.

Orchestrates the full conversational loop:

    User NL query
        → IntentParser       (parse intent + slot filling)
        → InputModifier      (modify CovariateSet / horizon)
        → ChronosForecastProvider  (re-run Chronos-2)
        → VerbalizationPipeline    (generate NL response via Extension 1)
        → DialogueResponse         (format response + delta vs original)

Usage::

    system = DialogueSystem(history=history_array, covariates=cov_set)
    response = system.query("What if we removed the marketing spend covariate?")
    print(response.answer)
    print(response.modification_description)
"""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

# Ensure repo root is in path so extension_1.* imports resolve correctly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from extension_1.attribution.types import CovariateSet
from extension_1.pipeline import PipelineResult, VerbalizationPipeline
from extension_1.config import PipelineConfig
from extension_1.evaluation.scoring import NLIConsistencyScorer
from extension_1.verbalization.template import TemplateVerbalizer
from extension_2.intent_parser import IntentParser, ParsedIntent
from extension_2.input_modifier import InputModifier, ModificationResult
from shared.forecast_provider import ChronosForecastProvider

logger = logging.getLogger(__name__)


# ──────────────── response dataclass ─────────────────────────────────

@dataclass
class DialogueResponse:
    """Output of a single dialogue turn.

    Attributes
    ----------
    query : str
        Original user query.
    intent : ParsedIntent
        Parsed intent from the query.
    modification : ModificationResult
        What was modified in the forecast inputs.
    answer : str
        Natural language response generated by the verbalization pipeline.
    consistency_score : float
        NLI faithfulness score of the answer.
    is_consistent : bool
        True if consistency_score >= threshold.
    delta_p50 : np.ndarray | None
        Difference in P50 between modified and original forecast.
        None if no modification was applied.
    original_forecast : dict | None
        Original P10/P50/P90 before modification.
    modified_forecast : dict | None
        Modified P10/P50/P90 after modification (same as original if unchanged).
    task_completed : bool
        True if intent was actionable and modification was applied successfully.
    """
    query: str
    intent: ParsedIntent
    modification: ModificationResult
    answer: str
    consistency_score: float
    is_consistent: bool
    delta_p50: Optional[np.ndarray]
    original_forecast: Optional[Dict[str, Any]]
    modified_forecast: Optional[Dict[str, Any]]
    task_completed: bool

    def summary(self) -> str:
        """Return a formatted summary for terminal display."""
        lines = [
            f"\n{'='*65}",
            f"  DIALOGUE RESPONSE",
            f"{'='*65}",
            f"\n  Query      : {self.query}",
            f"  Intent     : {self.intent.intent_type} "
            f"(confidence: {self.intent.confidence})",
        ]

        if self.intent.target_covariate:
            lines.append(f"  Covariate  : {self.intent.target_covariate}")
        if self.intent.scale_factor is not None:
            lines.append(f"  Scale      : {self.intent.scale_factor:.2f}")
        if self.intent.new_horizon is not None:
            lines.append(f"  New horizon: {self.intent.new_horizon}")

        lines.append(f"\n  Modification: {self.modification.description}")

        if self.delta_p50 is not None:
            mean_delta = float(np.mean(self.delta_p50))
            lines.append(
                f"  Delta P50  : mean={mean_delta:+.4f} "
                f"(min={float(np.min(self.delta_p50)):+.4f}, "
                f"max={float(np.max(self.delta_p50)):+.4f})"
            )

        lines.append(f"\n  Answer:\n   {self.answer}")
        lines.append(
            f"\n  Consistency: {self.consistency_score:.4f} "
            f"({'PASS' if self.is_consistent else 'FAIL'})"
        )
        lines.append(f"  Task completed: {self.task_completed}")
        lines.append("")
        return "\n".join(lines)


# ──────────────── dialogue system ────────────────────────────────────

class DialogueSystem:
    """Main dialogue system for interactive forecast interrogation.

    Maintains state across turns: the original history, the original
    forecast, and the current covariate set.

    Parameters
    ----------
    history : np.ndarray
        Historical time series values (1-D).
    covariates : CovariateSet | None
        Initial covariate set (may be None for univariate mode).
    horizon : int
        Initial forecast horizon in steps.
    seed : int
        Random seed for reproducibility.
    use_llm_fallback : bool
        Whether to use LLM tier for complex queries.
    """

    def __init__(
        self,
        history: np.ndarray,
        covariates: Optional[CovariateSet] = None,
        horizon: int = 14,
        seed: int = 42,
        use_llm_fallback: bool = False,
    ) -> None:
        self.history = np.asarray(history, dtype=np.float64)
        self.covariates = covariates
        self.horizon = horizon
        self.seed = seed

        covariate_names = covariates.names if covariates is not None else []

        # Build components
        config = PipelineConfig(seed=seed)
        self._provider = ChronosForecastProvider(enable_attention=True)
        self._pipeline = VerbalizationPipeline(
            forecast_provider=self._provider,
            verbalizer=TemplateVerbalizer(seed=seed),
            scorer=NLIConsistencyScorer(),
            config=config,
        )
        self._parser = IntentParser(
            covariate_names=covariate_names,
            use_llm_fallback=use_llm_fallback,
        )
        self._modifier = InputModifier(default_horizon=horizon)

        # Cache the original forecast
        self._original_result: Optional[PipelineResult] = None
        self._turn_history: List[DialogueResponse] = []

    def _get_original_forecast(self) -> PipelineResult:
        """Run and cache the original forecast (lazy evaluation)."""
        if self._original_result is None:
            logger.info("Computing original forecast (horizon=%d) ...", self.horizon)
            self._original_result = self._pipeline.run(
                self.history,
                horizon=self.horizon,
                covariates=self.covariates,
            )
        return self._original_result

    def query(self, user_query: str, *, dry_run: bool = False) -> DialogueResponse:
        """Process a natural language query and return a response.

        Parameters
        ----------
        user_query : str
            Raw user input string.
        dry_run : bool
            If True, parse the intent and apply the modification to update
            internal state, but skip Chronos-2 and verbalization. Useful
            for evaluation of parser and state-management logic without
            the cost of model inference.

        Returns
        -------
        DialogueResponse
            Full response with NL answer, delta, and metadata.
        """
        logger.info("Processing query: %s", user_query)

        # Parse intent (always — dry_run still needs this)
        intent = self._parser.parse(user_query)
        logger.info("Intent: %s (confidence=%s)", intent.intent_type, intent.confidence)

        # Apply modification to compute new state
        modification = self._modifier.apply(intent, self.covariates, self.horizon)

        if dry_run:
            # Persist state without running Chronos-2
            if modification.modified:
                self.covariates = modification.covariates
                self.horizon = modification.horizon
            response = DialogueResponse(
                query=user_query,
                intent=intent,
                modification=modification,
                answer="[dry run]",
                consistency_score=0.0,
                is_consistent=False,
                delta_p50=None,
                original_forecast=None,
                modified_forecast=None,
                task_completed=modification.modified and intent.is_actionable(),
            )
            self._turn_history.append(response)
            return response

        # Full path — ensure original forecast exists
        original = self._get_original_forecast()
        original_forecast = original.forecast

        # Handle query-only intents that don't require re-running the model
        if intent.intent_type == "confidence_query":
            return self._handle_confidence_query(
                user_query, intent, original, original_forecast
            )
        if intent.intent_type == "counterfactual":
            return self._handle_counterfactual(
                user_query, intent, original, original_forecast
            )

        # Re-run Chronos-2 with modified inputs if anything changed
        if modification.modified:
            logger.info("Re-running forecast with modified inputs ...")
            modified_result = self._pipeline.run(
                self.history,
                horizon=modification.horizon,
                covariates=modification.covariates,
            )
            modified_forecast = modified_result.forecast

            # Compute delta on P50 (align lengths)
            orig_p50 = np.asarray(original_forecast["p50"])
            mod_p50 = np.asarray(modified_forecast["p50"])
            min_len = min(len(orig_p50), len(mod_p50))
            delta_p50 = mod_p50[:min_len] - orig_p50[:min_len]

            answer = modified_result.verbalization.summary
            consistency_score = modified_result.consistency_report.overall_score
            is_consistent = modified_result.consistency_report.is_consistent
            task_completed = intent.is_actionable()

            # Persist updated inputs so subsequent turns build on this state
            self.covariates = modification.covariates
            self.horizon = modification.horizon

        else:
            # No modification — use original result
            modified_forecast = original_forecast
            delta_p50 = None
            answer = original.verbalization.summary
            consistency_score = original.consistency_report.overall_score
            is_consistent = original.consistency_report.is_consistent
            task_completed = False

        # Prepend modification description to answer
        if modification.description and modification.modified:
            answer = f"[{modification.description}] {answer}"

        response = DialogueResponse(
            query=user_query,
            intent=intent,
            modification=modification,
            answer=answer,
            consistency_score=consistency_score,
            is_consistent=is_consistent,
            delta_p50=delta_p50,
            original_forecast=original_forecast,
            modified_forecast=modified_forecast,
            task_completed=task_completed,
        )

        self._turn_history.append(response)
        return response

    def _handle_confidence_query(
        self,
        user_query: str,
        intent: ParsedIntent,
        original: PipelineResult,
        original_forecast: Dict[str, Any],
    ) -> DialogueResponse:
        """Handle a confidence/uncertainty query without re-running."""
        p10 = np.asarray(original_forecast["p10"])
        p50 = np.asarray(original_forecast["p50"])
        p90 = np.asarray(original_forecast["p90"])

        mean_width = float(np.mean(p90 - p10))
        rel_unc = mean_width / (float(np.mean(np.abs(p50))) + 1e-9)
        uncertainty_level = original.features.uncertainty_level
        uncertainty_trend = original.features.uncertainty_trend

        answer = (
            f"The forecast uncertainty is {uncertainty_level} and {uncertainty_trend}. "
            f"The mean prediction interval width (P10-P90) is {mean_width:.2f}, "
            f"representing {rel_unc*100:.1f}% of the forecast level. "
            f"The P10 (pessimistic) scenario is {float(np.mean(p10)):.2f} "
            f"and the P90 (optimistic) scenario is {float(np.mean(p90)):.2f} "
            f"on average over the forecast horizon."
        )

        modification = ModificationResult(
            covariates=self.covariates,
            horizon=self.horizon,
            description="Confidence query — no modification applied.",
            modified=False,
        )

        response = DialogueResponse(
            query=user_query,
            intent=intent,
            modification=modification,
            answer=answer,
            consistency_score=original.consistency_report.overall_score,
            is_consistent=original.consistency_report.is_consistent,
            delta_p50=None,
            original_forecast=original_forecast,
            modified_forecast=original_forecast,
            task_completed=True,
        )

        self._turn_history.append(response)
        return response

    def _handle_counterfactual(
        self,
        user_query: str,
        intent: ParsedIntent,
        original: PipelineResult,
        original_forecast: Dict[str, Any],
    ) -> DialogueResponse:
        """Handle a counterfactual query about historical inputs.

        The system only modifies future forecast inputs; it cannot alter
        historical data retroactively. This handler explains the limitation
        and points the user toward what the system can do instead.
        """
        cov = intent.target_covariate
        if cov:
            suggestion = (
                f"I cannot retroactively alter past values of '{cov}'. "
                f"However, I can show you what the forecast would look like "
                f"if '{cov}' were removed or scaled in future periods — "
                f"just ask me to remove or scale it."
            )
        else:
            suggestion = (
                "I can only modify future forecast inputs, not historical data. "
                "Try asking me to remove or scale a specific covariate, "
                "or to change the forecast horizon."
            )

        answer = (
            f"{suggestion} "
            f"For reference, the current forecast: {original.verbalization.summary}"
        )

        modification = ModificationResult(
            covariates=self.covariates,
            horizon=self.horizon,
            description="Counterfactual query — historical inputs cannot be modified.",
            modified=False,
        )

        response = DialogueResponse(
            query=user_query,
            intent=intent,
            modification=modification,
            answer=answer,
            consistency_score=original.consistency_report.overall_score,
            is_consistent=original.consistency_report.is_consistent,
            delta_p50=None,
            original_forecast=original_forecast,
            modified_forecast=original_forecast,
            task_completed=True,
        )

        self._turn_history.append(response)
        return response

    def reset(self) -> None:
        """Reset the dialogue state, clearing cached forecasts."""
        self._original_result = None
        self._turn_history = []
        logger.info("Dialogue system reset.")

    @property
    def turn_history(self) -> List[DialogueResponse]:
        """Return the list of all dialogue turns so far."""
        return list(self._turn_history)